name: Publish to npmjs.com

on:
  push:
    tags:
      - v*
    branches:
      - main
      - master

jobs:
  call-workflow:
    - uses: JameelKaisar/mwoffliner-test22/.github/workflows/test2.yml@master
    # - uses: ./.github/workflows/test.yml
      secrets:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # build:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://registry.npmjs.org'

  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
